"""
Author: L. Flygare
Description: provides helper functions for loading the projects json data and converting it into internal python 
             objects (Monster and Move)

             this module acts as the bridge between:
                -raw JSON data generated by pokeapi_loader.py (PokeAPI-derived), and
                -the runtime objects used by the application (battle engine, UI, etc.)

             responsibilities:
                -load monsters.json and construct Monster objects
                -load moves.json and construct Move objects
                -load move_learners.json to map Pokémon to their legal moves

             DOES NOT:
                -perform validation of battle rules
                -handle pp, fainting, damdage, or move legality
            
             ALL returned objects are ready for immediate use by battle_engine.py

"""

import json
from pathlib import Path
from typing import Dict, List

from .models import Monster, Move

#-----------------------------
# paths
#-----------------------------

#project root (folder above /core)
ROOT = Path(__file__).resolve().parents[1]

#directory where pokeapi_loader.py stores its output json files
DATA_DIR = ROOT / "data"

def load_monsters_json(path: str | None = None) -> Dict[str, Monster]:
    """
    load monsters.json and return a dict mapping from dex id to Monster objects
    
    expected JSON structure:
        {
            "#001": {
                "dex": "#001",
                "name": "Bulbasaur",
                "type1": "Grass",
                "type2": "Poison",
                "sprite": "<url or None>",
                "hp": 45,
                "atk": 49,
                "dfn": 49,
                "sp_atk": 65,
                "sp_dfn": 65,
                "speed": 45
            },
            ...
        }
    """
    p = Path(path) if path else DATA_DIR / "monsters.json"
    raw = json.loads(p.read_text(encoding = "utf-8"))

    monsters: Dict[str, Monster] = {}
    for dex, data in raw.items():
        monsters[dex] = Monster(
            dex = data["dex"], 
            name = data["name"], 
            type1 = data["type1"], 
            type2 = data.get("type2"),      #may be None
            sprite = data.get("sprite"),    #includes pokeapi sprite url - may be None
            hp = data["hp"], 
            atk = data["atk"], 
            dfn = data["dfn"], 
            sp_atk = data["sp_atk"], 
            sp_dfn = data["sp_dfn"], 
            speed = data["speed"], 
        )
    return monsters

def load_moves_json(path: str | None = None) -> Dict[str, Move]:
    """
    load moves.json and returns a dict mapping from move name to Move objects

    notes:
        -status moves are represented by power=None.
        -accuracy and PP values come directly from PokeAPI-derived data.
        -these Move objects represent *base move data* and are copied
          per battle to track PP independently.    
    """
    p = Path(path) if path else DATA_DIR / "moves.json"
    raw = json.loads(p.read_text(encoding = "utf-8"))

    moves: Dict[str, Move] = {}
    for name, data in raw.items():
        moves[name] = Move(
            name = data["name"], 
            type = data["type"], 
            power = data["power"], 
            accuracy = data["accuracy"], 
            pp = data["pp"], 
        )
    return moves

def load_move_learners_json(path: str | None = None) -> Dict[str, List[str]]:
    """
    load move_learners.json and returns a dict mapping pokemon to their legal moves
        
    the returned structure maps each dex id to an ordered list of move names
    that the Pokémon can learn (typically via level-up in Gen 1).

    this data is used to:
        -build default move sets for battles
        -display move previews in the Team Builder UI
        -enforce move legality without hardcoding rules
    """
    p = Path(path) if path else DATA_DIR / "move_learners.json"
    raw = json.loads(p.read_text(encoding = "utf-8"))

    return {dex: list(moves) for dex, moves in raw.items()}

